In [1]:
import pandas as pd

In [2]:
import matplotlib.pyplot as plt

In [3]:
add = 'D:\data\data\stage4.xlsx'

In [4]:
data1 =  pd.read_excel(add,sheet_name = 0,index_col=0)
data1

              企业名称 投资阶段          机构名称        投资时间
8             爱高集团  成熟期            黑石  1993-12-01
46           无锡小天鹅  成熟期          国泰财富  1995-09-01
47           无锡小天鹅  成熟期          华登国际  1995-09-01
49            风华高科  成熟期  广东风险投资（粤科金融）  1995-10-01
103    国风药业（原青岛中药）  成熟期          葳尔资本  1998-01-01
...            ...  ...           ...         ...
31706         世纪星源  成熟期          联德创投  2015-12-30
31707         同是科技  成熟期          邦明资本  2015-12-30
31713         神州优车  成熟期          君联资本  2015-12-30
31714         神州优车  成熟期          君联资本  2015-12-30
31727         万古科技  成熟期          华卓投资  2015-12-31

[6019 rows x 4 columns]

In [5]:
dataa = data1['投资时间']
dataa = set(dataa)
dataa = list(dataa)
dataa.sort()
dataa

['1993-12-01',
 '1995-09-01',
 '1995-10-01',
 '1998-01-01',
 '1998-05-01',
 '1998-05-26',
 '1999-01-01',
 '1999-01-15',
 '1999-08-01',
 '1999-10-01',
 '1999-11-01',
 '1999-11-16',
 '1999-12-01',
 '2000-06-29',
 '2000-07-01',
 '2000-07-12',
 '2000-08-01',
 '2000-08-15',
 '2000-10-27',
 '2000-12-01',
 '2001-01-01',
 '2001-03-01',
 '2001-04-24',
 '2001-06-01',
 '2001-07-01',
 '2001-07-14',
 '2001-09-01',
 '2001-11-01',
 '2001-12-29',
 '2002-01-01',
 '2002-04-01',
 '2002-04-02',
 '2002-04-09',
 '2002-08-01',
 '2002-09-12',
 '2002-10-17',
 '2002-10-19',
 '2002-12-01',
 '2003-01-01',
 '2003-01-07',
 '2003-02-01',
 '2003-02-28',
 '2003-04-08',
 '2003-05-01',
 '2003-06-09',
 '2003-06-12',
 '2003-07-16',
 '2003-07-23',
 '2003-08-01',
 '2003-08-29',
 '2003-09-01',
 '2003-10-01',
 '2003-11-01',
 '2003-11-12',
 '2003-12-31',
 '2004-01-01',
 '2004-01-07',
 '2004-01-19',
 '2004-02-01',
 '2004-02-16',
 '2004-03-01',
 '2004-03-03',
 '2004-04-01',
 '2004-05-24',
 '2004-06-01',
 '2004-06-29',
 '2004-07-27',
 '2004-08-01',
 '2004-08-06',
 '2004-08-13',
 '2004-09-01',
 '2004-10-01',
 '2004-10-13',
 '2004-10-24',
 '2004-10-26',
 '2004-10-29',
 '2004-11-01',
 '2004-11-09',
 '2004-12-01',
 '2004-12-11',
 '2004-12-31',
 '2005-01-01',
 '2005-01-28',
 '2005-03-01',
 '2005-03-07',
 '2005-03-31',
 '2005-04-01',
 '2005-04-20',
 '2005-05-01',
 '2005-05-17',
 '2005-06-01',
 '2005-06-10',
 '2005-06-20',
 '2005-06-22',
 '2005-07-01',
 '2005-08-01',
 '2005-08-11',
 '2005-08-15',
 '2005-08-25',
 '2005-08-29',
 '2005-09-01',
 '2005-09-09',
 '2005-09-26',
 '2005-10-01',
 '2005-10-24',
 '2005-10-27',
 '2005-10-31',
 '2005-11-01',
 '2005-11-15',
 '2005-12-01',
 '2005-12-03',
 '2005-12-13',
 '2005-12-14',
 '2005-12-31',
 '2006-01-01',
 '2006-01-18',
 '2006-01-23',
 '2006-01-26',
 '2006-02-01',
 '2006-03-01',
 '2006-03-13',
 '2006-03-15',
 '2006-04-01',
 '2006-04-13',
 '2006-04-24',
 '2006-05-01',
 '2006-05-11',
 '2006-05-25',
 '2006-05-29',
 '2006-06-01',
 '2006-06-29',
 '2006-06-30',
 '2006-07-01',
 '2006-08-01',
 '2006-08-02',
 '2006-08-24',
 '2006-08-25',
 '2006-08-31',
 '2006-09-01',
 '2006-09-21',
 '2006-09-28',
 '2006-10-04',
 '2006-10-16',
 '2006-10-17',
 '2006-10-26',
 '2006-10-27',
 '2006-11-01',
 '2006-11-02',
 '2006-11-07',
 '2006-11-15',
 '2006-11-17',
 '2006-11-26',
 '2006-11-27',
 '2006-11-30',
 '2006-12-01',
 '2006-12-06',
 '2006-12-11',
 '2006-12-14',
 '2006-12-15',
 '2006-12-18',
 '2006-12-22',
 '2006-12-27',
 '2006-12-31',
 '2007-01-01',
 '2007-01-08',
 '2007-01-10',
 '2007-01-11',
 '2007-01-13',
 '2007-01-16',
 '2007-01-17',
 '2007-01-18',
 '2007-01-21',
 '2007-01-24',
 '2007-02-01',
 '2007-02-07',
 '2007-02-08',
 '2007-02-26',
 '2007-03-01',
 '2007-03-08',
 '2007-03-09',
 '2007-03-13',
 '2007-03-15',
 '2007-03-26',
 '2007-03-28',
 '2007-03-30',
 '2007-04-01',
 '2007-04-03',
 '2007-04-04',
 '2007-04-16',
 '2007-04-18',
 '2007-04-30',
 '2007-05-01',
 '2007-05-02',
 '2007-05-08',
 '2007-05-18',
 '2007-05-28',
 '2007-05-29',
 '2007-05-31',
 '2007-06-01',
 '2007-06-06',
 '2007-06-08',
 '2007-06-11',
 '2007-06-13',
 '2007-06-14',
 '2007-06-17',
 '2007-06-22',
 '2007-07-01',
 '2007-07-13',
 '2007-07-17',
 '2007-07-20',
 '2007-07-24',
 '2007-07-26',
 '2007-07-27',
 '2007-07-30',
 '2007-08-01',
 '2007-08-02',
 '2007-08-13',
 '2007-08-24',
 '2007-08-28',
 '2007-08-29',
 '2007-09-01',
 '2007-09-05',
 '2007-09-07',
 '2007-09-11',
 '2007-09-12',
 '2007-09-18',
 '2007-09-21',
 '2007-09-24',
 '2007-09-27',
 '2007-09-28',
 '2007-10-01',
 '2007-10-09',
 '2007-10-10',
 '2007-10-14',
 '2007-10-19',
 '2007-10-23',
 '2007-10-24',
 '2007-11-01',
 '2007-11-02',
 '2007-11-06',
 '2007-11-07',
 '2007-11-09',
 '2007-11-12',
 '2007-11-14',
 '2007-11-16',
 '2007-11-21',
 '2007-11-22',
 '2007-11-27',
 '2007-11-29',
 '2007-11-30',
 '2007-12-01',
 '2007-12-05',
 '2007-12-11',
 '2007-12-14',
 '2007-12-15',
 '2007-12-17',
 '2007-12-18',
 '2007-12-19',
 '2007-12-20',
 '2007-12-26',
 '2007-12-28',
 '2008-01-01',
 '2008-01-08',
 '2008-01-09',
 '2008-01-10',
 '2008-01-14',
 '2008-01-16',
 '2008-01-22',
 '2008-01-26',
 '2008-01-29',
 '2008-02-01',
 '2008-02-05',
 '2008-02-27',
 '2008-03-01',
 '2008-03-10',
 '2008-03-11',
 '2008-03-14',
 '2008-03-22',
 '2008-03-31',
 '2008-04-01',
 '2008-04-08',
 '2008-04-09',
 '2008-04-15',
 '2008-04-16',
 '2008-04-17',
 '2008-04-18',
 '2008-04-19',
 '2008-04-28',
 '2008-04-29',
 '2008-05-01',
 '2008-05-16',
 '2008-05-20',
 '2008-05-22',
 '2008-05-23',
 '2008-05-25',
 '2008-05-26',
 '2008-05-28',
 '2008-05-30',
 '2008-06-01',
 '2008-06-05',
 '2008-06-15',
 '2008-06-17',
 '2008-06-18',
 '2008-06-26',
 '2008-06-30',
 '2008-07-01',
 '2008-07-02',
 '2008-07-08',
 '2008-07-10',
 '2008-07-16',
 '2008-07-18',
 '2008-07-21',
 '2008-07-28',
 '2008-08-01',
 '2008-08-08',
 '2008-08-10',
 '2008-08-15',
 '2008-08-27',
 '2008-09-01',
 '2008-09-04',
 '2008-09-08',
 '2008-09-11',
 '2008-09-20',
 '2008-09-23',
 '2008-09-25',
 '2008-09-28',
 '2008-10-01',
 '2008-10-09',
 '2008-10-12',
 '2008-10-16',
 '2008-10-28',
 '2008-11-01',
 '2008-11-03',
 '2008-11-06',
 '2008-11-20',
 '2008-11-21',
 '2008-12-01',
 '2008-12-08',
 '2008-12-12',
 '2008-12-18',
 '2008-12-24',
 '2008-12-26',
 '2008-12-29',
 '2008-12-31',
 '2009-01-01',
 '2009-01-06',
 '2009-01-07',
 '2009-01-12',
 '2009-01-17',
 '2009-01-20',
 '2009-02-01',
 '2009-02-04',
 '2009-02-05',
 '2009-02-06',
 '2009-02-18',
 '2009-02-20',
 '2009-02-26',
 '2009-03-01',
 '2009-03-05',
 '2009-03-26',
 '2009-03-27',
 '2009-03-30',
 '2009-04-01',
 '2009-04-07',
 '2009-04-10',
 '2009-04-13',
 '2009-04-16',
 '2009-04-20',
 '2009-04-23',
 '2009-04-28',
 '2009-05-01',
 '2009-05-05',
 '2009-05-11',
 '2009-05-14',
 '2009-05-15',
 '2009-05-18',
 '2009-05-19',
 '2009-05-20',
 '2009-05-21',
 '2009-05-25',
 '2009-05-27',
 '2009-06-01',
 '2009-06-03',
 '2009-06-10',
 '2009-06-12',
 '2009-06-15',
 '2009-06-17',
 '2009-06-18',
 '2009-06-19',
 '2009-06-20',
 '2009-06-22',
 '2009-06-23',
 '2009-06-24',
 '2009-06-25',
 '2009-06-26',
 '2009-06-29',
 '2009-06-30',
 '2009-07-01',
 '2009-07-03',
 '2009-07-04',
 '2009-07-08',
 '2009-07-10',
 '2009-07-14',
 '2009-07-25',
 '2009-07-29',
 '2009-07-31',
 '2009-08-01',
 '2009-08-03',
 '2009-08-04',
 '2009-08-06',
 '2009-08-10',
 '2009-08-11',
 '2009-08-12',
 '2009-08-13',
 '2009-08-15',
 '2009-08-17',
 '2009-08-20',
 '2009-08-24',
 '2009-08-25',
 '2009-08-27',
 '2009-08-28',
 '2009-08-31',
 '2009-09-01',
 '2009-09-07',
 '2009-09-09',
 '2009-09-12',
 '2009-09-15',
 '2009-09-17',
 '2009-09-18',
 '2009-09-20',
 '2009-09-22',
 '2009-09-23',
 '2009-09-24',
 '2009-09-26',
 '2009-09-27',
 '2009-09-28',
 '2009-09-29',
 '2009-09-30',
 '2009-10-01',
 '2009-10-15',
 '2009-10-19',
 '2009-10-20',
 '2009-10-21',
 '2009-10-23',
 '2009-10-25',
 '2009-10-26',
 '2009-10-28',
 '2009-10-29',
 '2009-10-30',
 '2009-11-01',
 '2009-11-03',
 '2009-11-05',
 '2009-11-06',
 '2009-11-09',
 '2009-11-11',
 '2009-11-12',
 '2009-11-19',
 '2009-11-21',
 '2009-11-23',
 '2009-11-25',
 '2009-11-26',
 '2009-11-27',
 '2009-11-30',
 '2009-12-01',
 '2009-12-03',
 '2009-12-06',
 '2009-12-07',
 '2009-12-10',
 '2009-12-11',
 '2009-12-14',
 '2009-12-16',
 '2009-12-17',
 '2009-12-18',
 '2009-12-20',
 '2009-12-22',
 '2009-12-23',
 '2009-12-24',
 '2009-12-25',
 '2009-12-28',
 '2009-12-29',
 '2009-12-31',
 '2010-01-01',
 '2010-01-04',
 '2010-01-05',
 '2010-01-06',
 '2010-01-07',
 '2010-01-13',
 '2010-01-15',
 '2010-01-21',
 '2010-01-26',
 '2010-01-27',
 '2010-01-31',
 '2010-02-01',
 '2010-02-02',
 '2010-02-04',
 '2010-02-05',
 '2010-02-08',
 '2010-02-09',
 '2010-02-12',
 '2010-02-18',
 '2010-02-22',
 '2010-02-24',
 '2010-02-26',
 '2010-03-01',
 '2010-03-02',
 '2010-03-04',
 '2010-03-08',
 '2010-03-10',
 '2010-03-11',
 '2010-03-12',
 '2010-03-15',
 '2010-03-16',
 '2010-03-17',
 '2010-03-18',
 '2010-03-19',
 '2010-03-20',
 '2010-03-22',
 '2010-03-23',
 '2010-03-25',
 '2010-03-26',
 '2010-03-29',
 '2010-03-30',
 '2010-03-31',
 '2010-04-01',
 '2010-04-06',
 '2010-04-07',
 '2010-04-14',
 '2010-04-18',
 '2010-04-20',
 '2010-04-21',
 '2010-04-26',
 '2010-04-27',
 '2010-04-28',
 '2010-04-29',
 '2010-04-30',
 '2010-05-06',
 '2010-05-10',
 '2010-05-11',
 '2010-05-12',
 '2010-05-13',
 '2010-05-16',
 '2010-05-17',
 '2010-05-18',
 '2010-05-20',
 '2010-05-21',
 '2010-05-24',
 '2010-05-25',
 '2010-05-26',
 '2010-05-27',
 '2010-05-28',
 '2010-05-31',
 '2010-06-01',
 '2010-06-03',
 '2010-06-09',
 '2010-06-11',
 '2010-06-17',
 '2010-06-18',
 '2010-06-19',
 '2010-06-22',
 '2010-06-23',
 '2010-06-24',
 '2010-06-25',
 '2010-06-27',
 '2010-06-28',
 '2010-06-29',
 '2010-06-30',
 '2010-07-01',
 '2010-07-02',
 '2010-07-03',
 '2010-07-06',
 '2010-07-09',
 '2010-07-12',
 '2010-07-13',
 '2010-07-14',
 '2010-07-16',
 '2010-07-17',
 '2010-07-20',
 '2010-07-21',
 '2010-07-22',
 '2010-07-23',
 '2010-07-28',
 '2010-07-29',
 '2010-07-30',
 '2010-08-01',
 '2010-08-04',
 '2010-08-05',
 '2010-08-06',
 '2010-08-11',
 '2010-08-12',
 '2010-08-13',
 '2010-08-15',
 '2010-08-17',
 '2010-08-20',
 '2010-08-23',
 '2010-08-24',
 '2010-08-26',
 '2010-08-27',
 '2010-08-30',
 '2010-08-31',
 '2010-09-01',
 '2010-09-02',
 '2010-09-03',
 '2010-09-06',
 '2010-09-07',
 '2010-09-10',
 '2010-09-11',
 '2010-09-13',
 '2010-09-14',
 '2010-09-15',
 '2010-09-16',
 '2010-09-17',
 '2010-09-18',
 '2010-09-19',
 '2010-09-20',
 '2010-09-21',
 '2010-09-24',
 '2010-09-26',
 '2010-09-27',
 '2010-09-29',
 '2010-09-30',
 '2010-10-01',
 '2010-10-04',
 '2010-10-08',
 '2010-10-10',
 '2010-10-13',
 '2010-10-14',
 '2010-10-16',
 '2010-10-18',
 '2010-10-20',
 '2010-10-21',
 '2010-10-22',
 '2010-10-25',
 '2010-10-26',
 '2010-10-27',
 '2010-10-28',
 '2010-10-29',
 '2010-11-01',
 '2010-11-02',
 '2010-11-05',
 '2010-11-08',
 '2010-11-09',
 '2010-11-10',
 '2010-11-12',
 '2010-11-15',
 '2010-11-18',
 '2010-11-19',
 '2010-11-23',
 '2010-11-24',
 '2010-11-25',
 '2010-11-30',
 '2010-12-01',
 '2010-12-02',
 '2010-12-03',
 '2010-12-04',
 '2010-12-06',
 '2010-12-07',
 '2010-12-09',
 '2010-12-10',
 '2010-12-13',
 '2010-12-14',
 '2010-12-15',
 '2010-12-16',
 '2010-12-17',
 '2010-12-18',
 '2010-12-20',
 '2010-12-21',
 '2010-12-23',
 '2010-12-24',
 '2010-12-25',
 '2010-12-27',
 '2010-12-28',
 '2010-12-29',
 '2010-12-30',
 '2010-12-31',
 '2011-01-01',
 '2011-01-03',
 '2011-01-05',
 '2011-01-06',
 '2011-01-10',
 '2011-01-11',
 '2011-01-12',
 '2011-01-13',
 '2011-01-14',
 '2011-01-15',
 '2011-01-16',
 '2011-01-17',
 '2011-01-18',
 '2011-01-19',
 '2011-01-20',
 '2011-01-21',
 '2011-01-24',
 '2011-01-25',
 '2011-01-26',
 '2011-01-27',
 '2011-01-28',
 '2011-01-29',
 '2011-02-01',
 '2011-02-10',
 '2011-02-11',
 '2011-02-14',
 '2011-02-16',
 '2011-02-17',
 '2011-02-18',
 '2011-02-22',
 '2011-02-24',
 '2011-03-01',
 '2011-03-02',
 '2011-03-03',
 '2011-03-05',
 '2011-03-06',
 '2011-03-07',
 '2011-03-08',
 '2011-03-09',
 '2011-03-11',
 '2011-03-12',
 '2011-03-14',
 '2011-03-15',
 '2011-03-16',
 '2011-03-21',
 '2011-03-22',
 '2011-03-23',
 '2011-03-24',
 '2011-03-25',
 '2011-03-28',
 '2011-03-29',
 '2011-03-30',
 '2011-03-31',
 '2011-04-01',
 '2011-04-07',
 '2011-04-11',
 '2011-04-12',
 '2011-04-15',
 '2011-04-16',
 '2011-04-18',
 '2011-04-19',
 '2011-04-20',
 '2011-04-21',
 '2011-04-22',
 '2011-04-26',
 '2011-04-27',
 '2011-04-28',
 '2011-04-29',
 '2011-04-30',
 '2011-05-01',
 '2011-05-04',
 '2011-05-05',
 '2011-05-06',
 '2011-05-10',
 '2011-05-11',
 '2011-05-13',
 '2011-05-17',
 '2011-05-19',
 '2011-05-20',
 '2011-05-21',
 '2011-05-22',
 '2011-05-23',
 '2011-05-24',
 '2011-05-25',
 '2011-05-26',
 '2011-05-27',
 '2011-05-30',
 '2011-05-31',
 '2011-06-01',
 '2011-06-02',
 '2011-06-03',
 '2011-06-04',
 '2011-06-07',
 '2011-06-08',
 '2011-06-09',
 '2011-06-10',
 '2011-06-11',
 '2011-06-14',
 '2011-06-15',
 '2011-06-16',
 '2011-06-17',
 '2011-06-20',
 '2011-06-21',
 '2011-06-23',
 '2011-06-24',
 '2011-06-27',
 '2011-06-28',
 '2011-06-30',
 '2011-07-01',
 '2011-07-03',
 '2011-07-04',
 '2011-07-05',
 '2011-07-06',
 '2011-07-07',
 '2011-07-08',
 '2011-07-11',
 '2011-07-13',
 '2011-07-14',
 '2011-07-15',
 '2011-07-18',
 '2011-07-19',
 '2011-07-20',
 '2011-07-21',
 '2011-07-22',
 '2011-07-25',
 '2011-07-26',
 '2011-07-28',
 '2011-07-29',
 '2011-07-31',
 '2011-08-01',
 '2011-08-03',
 '2011-08-08',
 '2011-08-10',
 '2011-08-11',
 '2011-08-12',
 '2011-08-14',
 '2011-08-15',
 '2011-08-16',
 '2011-08-17',
 '2011-08-22',
 '2011-08-24',
 '2011-08-25',
 '2011-08-26',
 '2011-08-28',
 '2011-08-29',
 '2011-08-30',
 '2011-08-31',
 '2011-09-01',
 '2011-09-05',
 '2011-09-06',
 '2011-09-09',
 '2011-09-11',
 '2011-09-14',
 '2011-09-16',
 '2011-09-19',
 '2011-09-20',
 '2011-09-22',
 '2011-09-23',
 '2011-09-26',
 '2011-09-27',
 '2011-09-28',
 '2011-09-29',
 '2011-09-30',
 '2011-10-01',
 '2011-10-06',
 '2011-10-10',
 '2011-10-11',
 '2011-10-12',
 '2011-10-13',
 '2011-10-17',
 '2011-10-18',
 '2011-10-19',
 '2011-10-24',
 '2011-10-25',
 '2011-11-01',
 '2011-11-02',
 '2011-11-04',
 '2011-11-08',
 '2011-11-09',
 '2011-11-11',
 '2011-11-14',
 '2011-11-15',
 '2011-11-17',
 '2011-11-18',
 '2011-11-21',
 '2011-11-22',
 '2011-11-23',
 '2011-11-24',
 '2011-11-27',
 '2011-11-28',
 '2011-11-29',
 '2011-11-30',
 '2011-12-01',
 '2011-12-02',
 '2011-12-06',
 '2011-12-07',
 '2011-12-08',
 '2011-12-09',
 '2011-12-11',
 '2011-12-12',
 '2011-12-13',
 '2011-12-14',
 '2011-12-15',
 '2011-12-16',
 '2011-12-18',
 '2011-12-20',
 '2011-12-21',
 '2011-12-22',
 '2011-12-23',
 '2011-12-26',
 '2011-12-27',
 '2011-12-30',
 '2011-12-31',
 '2012-01-01',
 '2012-01-04',
 '2012-01-05',
 '2012-01-06',
 '2012-01-08',
 '2012-01-10',
 '2012-01-12',
 '2012-01-13',
 '2012-01-15',
 '2012-01-16',
 '2012-01-18',
 '2012-01-19',
 '2012-01-20',
 '2012-01-26',
 '2012-02-01',
 '2012-02-03',
 '2012-02-06',
 '2012-02-07',
 '2012-02-08',
 '2012-02-10',
 '2012-02-13',
 '2012-02-14',
 '2012-02-15',
 '2012-02-16',
 '2012-02-20',
 '2012-02-23',
 '2012-02-24',
 '2012-02-27',
 '2012-02-29',
 '2012-03-01',
 '2012-03-03',
 '2012-03-05',
 '2012-03-06',
 '2012-03-08',
 '2012-03-09',
 '2012-03-12',
 '2012-03-13',
 '2012-03-15',
 '2012-03-16',
 '2012-03-19',
 '2012-03-20',
 '2012-03-21',
 '2012-03-22',
 '2012-03-23',
 '2012-03-25',
 '2012-03-26',
 '2012-03-29',
 '2012-03-30',
 '2012-03-31',
 '2012-04-01',
 '2012-04-03',
 '2012-04-05',
 '2012-04-06',
 '2012-04-07',
 '2012-04-08',
 '2012-04-09',
 '2012-04-10',
 '2012-04-11',
 '2012-04-12',
 '2012-04-13',
 '2012-04-15',
 '2012-04-16',
 '2012-04-17',
 '2012-04-19',
 '2012-04-20',
 '2012-04-23',
 '2012-04-24',
 '2012-04-25',
 '2012-04-26',
 '2012-04-27',
 '2012-04-30',
 '2012-05-01',
 '2012-05-02',
 '2012-05-05',
 '2012-05-07',
 '2012-05-08',
 '2012-05-09',
 '2012-05-10',
 '2012-05-11',
 '2012-05-13',
 '2012-05-14',
 '2012-05-15',
 '2012-05-17',
 '2012-05-18',
 '2012-05-19',
 '2012-05-20',
 '2012-05-21',
 '2012-05-22',
 '2012-05-24',
 '2012-05-25',
 '2012-05-26',
 '2012-05-28',
 '2012-05-31',
 '2012-06-01',
 '2012-06-04',
 '2012-06-05',
 '2012-06-07',
 '2012-06-08',
 '2012-06-09',
 '2012-06-10',
 '2012-06-12',
 '2012-06-15',
 '2012-06-17',
 '2012-06-18',
 '2012-06-19',
 '2012-06-20',
 '2012-06-21',
 '2012-06-25',
 '2012-06-26',
 '2012-06-27',
 '2012-06-28',
 '2012-06-29',
 '2012-06-30',
 ...]

In [6]:
data1.set_index('投资时间',drop=True, append=False, inplace=True)

In [7]:
ans = 0
df = pd.DataFrame()
for i in dataa:
    x = data1.loc[i]
    if isinstance(x,pd.Series)== True:
            continue
    if ans == 0:
        x.set_index('企业名称',drop=False, append=False, inplace=True)
    else :
        ans=ans+1
    
    y = x['企业名称']
    y = set(y)
    y = list(y)
    y.sort()

    
    for j in y:
        z = x.loc[j]
        
        if isinstance(z,pd.Series)== True:
            continue
        else:
            zz = z['机构名称']
            zz = set(zz)
            zz = list(zz)
            zz.sort()
#            print(zz)
#            print('\n')
            
            for i1 in range(len(zz)):
                for i2 in range(i1+1,len(zz)):
                    x1 = zz[i1]
                    x2 = zz[i2]
                    c={'投资次数':1,
                       '机构名称1':x1,
                       '机构名称2':x2}
                    
                    df1 = pd.DataFrame(c,index=[0])
                    df = df.append(df1, ignore_index=True)

In [8]:
df

      投资次数    机构名称1 机构名称2
0        1     华登国际  国泰财富
1        1     上海永宣  华登国际
2        1  GIC特殊投资    中金
3        1  GIC特殊投资  华登国际
4        1       中金  华登国际
...    ...      ...   ...
3008     1     泰恒投资   赛伯乐
3009     1     浙科投资  联德创投
3010     1     浙科投资   赛伯乐
3011     1     联德创投   赛伯乐
3012     1     创祥投资  天源投资

[3013 rows x 3 columns]

In [9]:
    df.to_excel('Stage14.xlsx')